Controllers/UpdateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationMVC.Controllers
{
    public class UpdateController : Controller
    {
        // GET: Update
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationMVC.Models;
using System.Data.Entity;

namespace WebApplicationMVC.Controllers
{
    public class UserController : Controller
    {
        ReleaseManagementContext db = new ReleaseManagementContext();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(LoginDetails loginDetails)
        {
            //ReleaseManagementContext db = new ReleaseManagementContext();
            try
            {
                db.EloginDetails.Add(loginDetails);
                db.SaveChanges();
                ViewBag.msg = "User created";
            }
            catch (Exception ex)
            {

                ViewBag.msg = ex.Message;
            }
            return View();
        }

       
       
            [HttpGet] // Set the attribute to Read 
            public ActionResult Read()
            {
                var data = db.EloginDetails.ToList();
                return View(data);
            
            }
        

        //public ActionResult Update()
        //{
        //    return View();
        //}


        public ActionResult Update(string id)
        {
            
                LoginDetails selecteddata = db.EloginDetails.Where(x => x.Username == id).SingleOrDefault();
                return View(selecteddata);
                
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(LoginDetails model)
        {
          
                

                LoginDetails data = db.EloginDetails.FirstOrDefault(x => x.Username == model.Username);

                
                if (data != null)
                {
                    data.Password = model.Password;
                    data.Role = model.Role;

                    db.SaveChanges();
                ViewBag.msg = "updated";
                    //return RedirectToAction("Read");
                }
                
                    return View();
            
        }

        public ActionResult Delete(string id)
        {
            LoginDetails data = db.EloginDetails.FirstOrDefault(x => x.Username == id);
            return View(data);
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteForm(string id)
        {
            
                LoginDetails data = db.EloginDetails.FirstOrDefault(x => x.Username == id);
                if (data != null)
                {
                    db.EloginDetails.Remove(data);
                    db.SaveChanges();
                    return RedirectToAction("Read");
                }
            ViewBag.de = "sorry";
                return View();
            
        }

        public ActionResult LoginUser(string id)
        {
            LoginDetails data = db.EloginDetails.FirstOrDefault(x => x.Username == id);
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginUser(LoginDetails details)
        {

            LoginDetails data = db.EloginDetails.FirstOrDefault(x => x.Username == details.Username);
            if (data != null)
            {
                
                if (data.Password == details.Password)
                {
                    TempData["welcome"] = "Welcome";
                    TempData["Username"] = data.Username;
                    TempData["role"] = data.Role;
                    //return RedirectToAction("Read");
                    //db.EloginDetails.Remove(data);
                    //db.SaveChanges();

                    return RedirectToAction("Read");
                }
            }

            if (data.Role == "manager")
            {
                ViewBag.p = "Welcome Manager!";
                return RedirectToAction("Read");
            }
            else if (data.Role == "developer")
            {
                ViewBag.p = "Welcome developer!";
                return RedirectToAction("Read");
            }
            else if (data.Role == "tester")
            {
                ViewBag.p = "Welcome tester!";
                return RedirectToAction("Read");
            }
            ViewBag.de = "invalid user";
            return View();

        }



    }
}

Views/User/Delete.cshtml
@model WebApplicationMVC.Models.LoginDetails

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>LoginDetails</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Role)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Role)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Read")
            </div>
        }
        <div>
            @ViewBag.de
        </div>
    </div>
</body>
</html>

Views/User/LoginUser.cshtml
@model WebApplicationMVC.Models.LoginDetails

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LoginUser</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>LoginDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
   
    <div>
        @ViewBag.de
        @*@Html.ActionLink("Back to List", "I")*@
    </div>
</body>
</html>

Views/User/Read.cshtml
@model IEnumerable<WebApplicationMVC.Models.LoginDetails>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Read</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Register")
    </p>
    <h3> @TempData.Peek("welcome")</h3>
    <h3> @TempData.Peek("Username")</h3>
    <h3> @TempData.Peek("role")</h3>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Update", new { id = item.Username }) |
                    @*@Html.ActionLink("Details", "Details", new { id=item.Username }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.Username })
                </td>
            </tr>

        }
        
    </table>


</body>
</html>

Views/User/Register.cshtml
@model WebApplicationMVC.Models.LoginDetails

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>LoginDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Read")
    </div>
</body>
</html>

Views/User/Update.cshtml
@model WebApplicationMVC.Models.LoginDetails

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>LoginDetails</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Username)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <duv>
        @ViewBag.msg
    </duv>
    <div>
        @Html.ActionLink("Back to List", "Read")
    </div>
</body>
</html>